version: "3"

services:
  jenkins:
    image: jenkins/jenkins:2.332.3-lts-jdk11
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
